name: Example Tests
# This workflow tests examples from the examples directory of this repo.

on:
  push:
    paths:
      - examples/**
  pull_request:
  workflow_dispatch:

jobs:
  example:
    strategy:
      fail-fast: false
      matrix:
        directory: [
            basic-mini, # testing cypress/included
            basic, # testing cypress/browsers
            chrome-for-testing,
            chromium,
            firefox-esr,
            included-as-non-root,
          ]
        os: [
            ubuntu-24.04, # testing Linux/amd64 platform
            ubuntu-24.04-arm, # testing Linux/arm64 platform
          ]
        exclude:
          - os: ubuntu-24.04-arm
            directory: chrome-for-testing # browser not available for Linux/arm64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
      - name: Run test script
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
